### ISSUE TITLE
Add helper to compute pixels in segment

### ISSUE THREAD

**Issue by yondonfu** [livepeer/lpms#125]
A broadcaster needs to be able to compute the pixels in a transcoded result for livepeer/go-livepeer#899.

This could involve adding a helper to the `ffmpeg` package:

```
func Pixels(input []byte) (int64, error)
```

This will likely require implementing the corresponding function in `ffmpeg/lpms_ffmpeg.c` that uses the ffmpeg C libraries for decoding the video and counting the frames.

**Comment by j0sh** [comment]
Rather than having a helper specialized around pixels alone, the helper could compute and populate the fields that exist in the `TranscodeResult` struct, and the caller can extract the information it needs such as the pixel count.

**Comment by j0sh** [comment]
Proposed implementation: to minimize additional C code [1], we can reuse our existing transcoder and pass in a null muxer along with codec copy [2] to minimize the work that needs to be done post-decode.

Building off the idea first proposed here https://github.com/livepeer/lpms/pull/146#pullrequestreview-275130706 : we can return a count of pixels decoded via the Transcode function, probably with the following signature:

```golang
type TranscodeResults {
  Decoded MediaInfo
  Encoded []MediaInfo
}

func Transcode4(input *TranscodeOptionsIn, ps []TranscodeOptions) (*TranscodeResults, error)
```

(May adjust the new Transcode3 function rather than introducing yet another one)

Working off https://github.com/livepeer/lpms/pull/122 - we can call the transcoder with codec copy and a null muxer. (ffmpeg has a null muxer, so we don't need to special-case any logic here.) Something like this:

```golang
type TranscodeOptions struct {
   // ... existing fields ...
   Encoder string
   Muxer string
}
func MediaInfo(string fname) (*MediaInfo, error) {
  in := &TranscodeOptionsIn{ Fname: fname }
  out := []TranscodeOptions{ TranscodeOptions { Oname: "-", Muxer: "null", Encoder: "copy" } }
  res, err := Transcode4(in, out)
  if err != nil {
    return err
  }
  return out[0].Decoded
}
```

[1] Minimizing the additional Cgo code not only improves composability and reusability, but also minimizes the error surface for accounting checks. Having separate implementations makes it more likely that counting discrepancies in one place or another would lead to accounting problems upstream. With this approach, any counting errors would be propagated through the system - so while we lose the double-checking that a separate implementation affords us, these errors should at least be consistent and not cause too many upstream discrepancies.

[2]  Building out more versatile transcoding configuration has been on the radar for a while. In particular, this would allow us to remove the segmenter-specific Cgo implementation in favor of a unified Cgo entry point for transcoding + segmentation. Since the same approach would also facilitate the implementation of this `MediaInfo` helper function, it seems like a good time to move forward with completing https://github.com/livepeer/lpms/pull/122 and https://github.com/livepeer/lpms/issues/55

**Comment by yondonfu** [comment]
The proposal sounds good to me. I just have one question: do you think the performance difference between calling `Transcode3()` with a null muxer and codec copy vs. writing additional C code specifically for decoding/computing `MediaInfo` on a file is negligible?

**Comment by j0sh** [comment]
Need to benchmark, but I suspect that yes, the overhead will be negligible. Will include some numbers in the PR so we understand the overhead implications.

Forgot to mention that we should implement codec copy before Streamflow anyway because currently we're re-encoding audio, but there's no way to verify audio at the moment. With codec copy, we should be able to do a bitexact check on each audio frame.

Re: #139 , I think it's still unclear what the best approach would be. Currently, the Cgo segmenter only returns after the stream stops (which would be matched by any unified Cgo entry point); another goroutine polls the filesystem for new segments and playlist changes. The best approach for #139 I can think of is to modify ffmpeg to incorporate pixel/frame info into the m3u8 headers, but I'm skeptical that such a specialized feature would be integrated upstream. Still need to think about it.

**Comment by j0sh** [comment]
I need to apologize - there was a logical inconsistency in the proposed implementation. When doing codec copy, there's no reason to decode (the segmenter does not decode, for example).

Worked around this by using a rawvideo encoder, which bascially copies the frame data as-is to the AVPacket for muxing to null. Luckily, the work for https://github.com/livepeer/lpms/pull/147 facilitated this flow without additional modifications... so here are some benchmarks.

The overhead compared to a specialized counter here is on the order of 8-10 % for a 8-second segment, and 12-13% for a 1-second segment (initialization constant factors account for the difference). This also includes audio decoding time, which wouldn't be included in a specialized implementation, which may improve things by another few percent - so we can probably assume this is ~15% slower in practice.

I'm not sure yet whether a 15% slowdown would be a deal breaker. It's not insignificant.

Benchmarked via this:
```golang
func BenchmarkDecodeOnly(b *testing.B) {

	run, dir := setupTest(b)
	defer os.RemoveAll(dir)

	// Prepare test environment : truncate input file
	cmd := `
        set -eux
        cd $0

        cp "$1/../transcoder/test.ts" inp.ts
        ffmpeg -i inp.ts -c:a copy -c:v copy -t 1 test.ts
    `
	run(cmd)

	InitFFmpeg()
	in := &TranscodeOptionsIn{Fname: dir + "/test.ts"}
	out := []TranscodeOptions{TranscodeOptions{
		Oname:        "-",
		Muxer:        ComponentOpts{Name: "null"},
		VideoEncoder: ComponentOpts{Name: "rawvideo"},
		Profile:      P720p30fps16x9, // needs to match input
	}}

	for i := 0; i < b.N; i++ {
		Transcode3(in, out)
	}
}
```

Simulating a decode-only approach was done by modifying the Cgo transcoder to skip everything after decoding:
```diff
diff --git a/ffmpeg/lpms_ffmpeg.c b/ffmpeg/lpms_ffmpeg.c
index 68c44a4..eaec615 100644
--- a/ffmpeg/lpms_ffmpeg.c
+++ b/ffmpeg/lpms_ffmpeg.c
@@ -834,6 +834,7 @@ int lpms_transcode(input_params *inp, output_params *params,
       decoded_results->frames++;
       decoded_results->pixels += dframe->width * dframe->height;
     }
+    goto whileloop_end;
 
     for (i = 0; i < nb_outputs; i++) {
       struct output_ctx *octx = &outputs[i];

```

One way to expedite this task would be to special-case some decode-only logic within the transcoder to skip processing any output if a special flag is passed in.

**Comment by yondonfu** [comment]
> The overhead compared to a specialized counter here is on the order of 8-10 % for a 8-second segment, and 12-13% for a 1-second segment (initialization constant factors account for the difference).

Do you have the actual time numbers for the rawvideo encoder approach vs. the specialized counter approach? If they're fairly small, it might be ok for now even given the relative overhead increase. If not, I would lean towards special casing the decode-only logic.

> One way to expedite this task would be to special-case some decode-only logic within the transcoder to skip processing any output if a special flag is passed in.

Could `lpms_transcode()` skip processing the output if `len(output_params) == 0`? Then, a caller that only cares about decoding would just omit any output params.

**Comment by j0sh** [comment]
> Could lpms_transcode() skip processing the output if len(output_params) == 0?

Yep - this is what I ended up doing: https://github.com/livepeer/lpms/pull/147/commits/9057730d68cda341de2046d17bb0f191285b4625
