### ISSUE TITLE
transcoding fails on segments containing very few video frames

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/lpms#168]
Got one segment that transcodes ok with software transcoding, but transcoding on Nvidia card produces incorrect output
Ffprobe's output for transcoded segment:
```
[mpeg @ 0x561cfc3d6e00] Format mpeg detected only with low score of 25, misdetection possible!
[mp2 @ 0x561cfc3d8840] Header missing
    Last message repeated 2 times
[mpeg @ 0x561cfc3d6e00] decoding for stream 0 failed
[mpeg @ 0x561cfc3d6e00] Could not find codec parameters for stream 0 (Audio: mp2, 0 channels, s16p): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpeg, from 'out_nv_0_out.ts':
  Duration: 00:00:00.02, start: 634.176011, bitrate: 453 kb/s
    Stream #0:0[0x1c0]: Audio: mp2, 0 channels, s16p
```
source segment:
[bad_video_bbb_sunflower_1080p_30fps_normal_t02mp4_057c3e76c81edee3a550_0_0_317_source.ts.gz](https://github.com/livepeer/lpms/files/4105368/bad_video_bbb_sunflower_1080p_30fps_normal_t02mp4_057c3e76c81edee3a550_0_0_317_source.ts.gz)
transcoded on Nvidia:
[out_nv_0_out.ts.gz](https://github.com/livepeer/lpms/files/4105375/out_nv_0_out.ts.gz)
software transcoded:
[out_sw_0_out.ts.gz](https://github.com/livepeer/lpms/files/4105376/out_sw_0_out.ts.gz)

**Comment by j0sh** [comment]
Nice one, this looks like a bug. There are only 3 video frames in the source, and the decoder doesn't return any of them by the time reading completes. Looks like we aren't flushing where we should in this case, because with nvidia, we depend on getting that first frame to use as a sentinel in order to drain the decoder.

Will have to think about this one. We might not necessarily want to close the decoder outright to flush, since re-opening it is expensive.

**Comment by darkdarkdragon** [comment]
[bad_video_ccb0eebc-2f55-497c-b10c-3a02cd578ba9_317_source.ts.gz](https://github.com/livepeer/lpms/files/4188982/bad_video_ccb0eebc-2f55-497c-b10c-3a02cd578ba9_317_source.ts.gz)

Another segment probably because of the same problem. Adding here because it produces output without video.

**Comment by AbAb1l** [comment]
For this particular segment, nvidia transcoding, the first `avcodec_receive_frame` call returns `AVERROR(EAGAIN)` and never returns the decoded frames unless we outright flush the decoder. I fear, to resolve this particular issue we would need to outright flush the decoder.

**Comment by iameli** [comment]
Here's another example file, this one containing exactly one video keyframe. https://storage.googleapis.com/docs.livepeer.live/eli/segment-debugging/32.ts

**Comment by iameli** [comment]
Looks like this occurs with CPU transcoding too - just reproduced with that 32.ts on a Mac laptop.

**Comment by iameli** [comment]
The error seems to go away if I add an audio track:

```
▶ curl -XPOST --data-binary @32.ts http://localhost:8936/live/test/1.ts -i
HTTP/1.1 100 Continue

HTTP/1.1 503 Service Unavailable
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 11 Mar 2020 06:23:07 GMT
Content-Length: 22

No sessions available

▶ ffmpeg -f lavfi -i "sine=frequency=1000" -i 32.ts -shortest -c:v copy -c:a aac 32_audio.ts
[snip]

▶ curl -XPOST --data-binary @32_audio.ts http://localhost:8936/live/test/1.ts -i
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Wed, 11 Mar 2020 06:24:17 GMT
Transfer-Encoding: chunked
```

Here's the resulting file. ffprobe confirms it's still a single frame: <https://storage.googleapis.com/docs.livepeer.live/eli/segment-debugging/32.ts>

**Comment by iameli** [comment]
Oh, lol, never mind — there's _only_ audio in the output file.

**Comment by jailuthra** [comment]
Currently, `lpms_ffmpeg.c` avoids _flushing_ the video decoder for every segment because it is expensive with NVDec. The current workaround [2] works fine unless the segment frame count is less than the internal decoder packet buffer. This is a proposal on how we can handle this.

###  Context
FFmpeg decoder keeps an internal buffer of packets `dpb`, before it starts returning frames. The flow is supposed to be like this:
* Send packet _1_ to decoder
* Receive frame
	* Throws error EAGAIN (gimme moar packet)
* Send packet _2_ to decoder
* Receive frame
	* Throws error EAGAIN (gimme moar packet)
* ...
* Send packet _dpb+1_ to decoder
* Receive frame
	* Returns decoded frame from packet _1_
* ...

When the encoded segment has less than `dpb` frames (or we don't have any more packets to send) we can **flush** the decoder.

### [1] Correct flushing
* Send a NULL packet to the decoder (or multiple) to start flushing mode
* Receive decoded frames until it throws AVERROR_EOF

### [2] Workaround flushing using a sentinel packet
* Send sentinel packet with `pts = -1`
* Receive decoded frames until:
	* We get back our sentinel packet
	* OR the decoder throws an error

This fails for the 3 frame segment with NVDec because the decoder is still throwing EAGAIN when we send it the sentinel packet (i.e. it just adds it to its buffer)

```
$ ./transcoding ~/Downloads/bad_video_bbb_sunflower_1080p_30fps_normal_t02mp4_057c3e76c81edee3a550_0_0_317_source.ts P240p30fps16x9 nv 0
Setting fname /home/darkapex/Downloads/bad_video_bbb_sunflower_1080p_30fps_normal_t02mp4_057c3e76c81edee3a550_0_0_317_source.ts encoding 1 renditions with nv
TRACE: lpms_transcode_new
TRACE: lpms_transcode
TRACE: transcode
	vid: 0, Sent packet pts 57075840, ret 0
	Recv frame pts 57075840, ret 0
	vid: 0, Sent packet pts 57077759, ret 0
	Recv frame pts 57077759, ret 0
	vid: 0, Sent packet pts 57079679, ret 0
	Recv frame pts 57079679, ret 0
	vid: 1, Sent packet pts 57080999, ret 0
	Recv frame pts -9223372036854775808, ret -11
	vid: 0, Sent packet pts 57081600, ret 0
	Recv frame pts 57081600, ret 0
	vid: 1, Sent packet pts 57087000, ret 0
	Recv frame pts -9223372036854775808, ret -11
	vid: 1, Sent packet pts 57083999, ret 0
	Recv frame pts -9223372036854775808, ret -11
	Sent sentinel packet, ret 0
	Recv frame pts -9223372036854775808, ret -11
Error feeding the filtergraph: Invalid argument
[aac @ 0x47657c0] 2 frames left in the queue on closing
TRACE: lpms_transcode_stop
profile=input frames=0 pixels=0
profile=P240p30fps16x9 frames=0 pixels=0
```

If we try decoding same segment but only 1 frame, it fails similarly even with Software decoder. Currently the Sofware decoder is also using the sentinel flushing even though it can do without it.
```
$ ./transcoding 1framebad.ts P240p30fps16x9 sw                                                                                                              
Setting fname 1framebad.ts encoding 1 renditions with sw
TRACE: lpms_transcode_new
TRACE: lpms_transcode
TRACE: transcode
	vid: 0, Sent packet pts 126841, ret 0
	Recv frame pts 126841, ret 0
	vid: 0, Sent packet pts 128761, ret 0
	Recv frame pts 128761, ret 0
	vid: 0, Sent packet pts 130681, ret 0
	Recv frame pts 130681, ret 0
	vid: 1, Sent packet pts 132000, ret 0
	Recv frame pts -9223372036854775808, ret -11
	Sent sentinel packet, ret 0
	Recv frame pts -9223372036854775808, ret -11
Error feeding the filtergraph: Invalid argument
TRACE: lpms_transcode_stop
profile=input frames=0 pixels=0
profile=P240p30fps16x9 frames=0 pixels=0
```

### Proposed Solution 1
Stop using the workaround and flush the decoder properly. This is clean but has a performance hit (how do I check this?)

### Proposed Solution 2
Flush for SW decoding. Keep sending sentinel packets for NVDec, but do it more robustly:
* Don't stop on first received EAGAIN, instead keep sending sentinel packets until we receive it back. Will this work? I have no idea :)

**Comment by j0sh** [comment]
We could flush properly via NULL only when necessary: eg, when the decoder has been initialized, the input has ended and we haven't received any frames. We'd have to reopen the decoder for the next segment though.

Note that we don't [initialize the decoder](https://github.com/livepeer/lpms/blob/6e167971ec68573d2cdf47cbb0b163fbb3a981a7/ffmpeg/lpms_ffmpeg.c#L833-L835) when doing stream copy exclusively, or if we don't have a stream, so the missing decoder case needs to be accounted for. And preferably checked via unit testing as well.

> has a performance hit (how do I check this?)

I've usually used printf / gettimeofday. Something like this:
```c
struct timeval start, end;
unsigned long long ms = 0;
gettimeofday(&start, NULL);
// something slow here
gettimeofday(&end, NULL);
ms = 1000*(end.tv_sec - start->tv_sec)+(end.tv_usec - start->tv_usec) / 1000;
printf("elapsed %llu ms\n", ms);
```

IIRC, most of the slowdown with nvdec is around initializing the HW context, especially under load. Don't recall precisely where, but maybe `av_hwframe_ctx_init` or thereabouts.

> Flush for SW decoding. Keep sending sentinel packets for NVDec

Slight preference for keeping the flows symmetrical, but am open to flushing properly if the cost of the extra decode outweighs the cost of re-initializing the decoder (the whole setup around [`open_input`](https://github.com/livepeer/lpms/blob/6e167971ec68573d2cdf47cbb0b163fbb3a981a7/ffmpeg/lpms_ffmpeg.c#L915-L956) has its own cost, including `avformat_find_stream_info` etc). Figuring that out is lower priority though.

**Comment by yondonfu** [comment]
Just noting that this issue is also causing pixel count verification to fail for an on-chain broadcaster. I'm currently transcoding using a [modified orchestrator](https://github.com/livepeer/go-livepeer/tree/eli/cpu-retry-hack-2) that retries with a backup [CPU transcoder](https://github.com/livepeer/go-livepeer/tree/eli/working-1frame). The CPU transcoder uses an older build of LPMS so it is able to handle the 1 frame segment. Whenever the orchestrator receives a 1 frame segment it uses the backup CPU transcoder and reports the # of encoded pixels to the broadcaster. But, the broadcaster uses a newer build of LPMS that is unable to handle the 1 frame segment and it gets a pixel count of 0 which causes pixel count verification to fail.
