### ISSUE TITLE
Add detection filter

### ISSUE THREAD

**Issue by oscar-davids** [livepeer/lpms#181]
## Abstract

Artificial intelligence is one of the most attractive technologies in the modern world. 
AI is an interdisciplinary science with multiple approaches, but advancements in machine learning and deep learning are creating a paradigm shift in virtually every sector of the tech industry. 
We can consider extended services that create value-added and provide advanced capabilities using this technology.

## Motivation

We have developed image classification filter using deep learning.
Considering that image classification and object detection technologies are used in many areas of life, 
We can expect extended services using image classify filter.

- for healthy and trust livepeer network
	Detecting offensive / adult images is an important problem for healthy network.
	When T or B detected these contents, we can report it with json format using a post API to the monitoring or policy server.
- for analysis consumer's trend and provide adapted service
	We can collect transcoding contents from T or B,so analyze trends every months and years, can provide adapted service.

I think these is objective of our project.

## Proposed Solution

While transcoding, detect contents whether indecent or not every given time or frames.
This function have to implement in c level because speed problem.
Once detected indecent contents, can report to the monitoring or policy server in go level.
Report format would be include following contents(who,when,what,how): Transcoder ID, UTC time, Contents, Probability

We can consider detection in B side, but the performance of B should be high.
Here descripts only T side implementation. 

## Implementation Tasks and Considerations

- C Level

Currently, transcoding function have been implemented using ffmpeg library.

https://github.com/livepeer/lpms/blob/d03c749890cbbe028ab6daedf4855b711354abfd/ffmpeg/lpms_ffmpeg.c#L1116

Avoid duplication decoding, have to insert detection function in "transcode" function, after "process_in" function.

https://github.com/livepeer/lpms/blob/d03c749890cbbe028ab6daedf4855b711354abfd/ffmpeg/lpms_ffmpeg.c#L1206

probability = process_detection(ictx, dframe);

if probability returned is bigger than certain threshold, we can confirm this frame as indecent one.
Threshold > 0.8 indicate that the image is highly probable to be indecent content , accuracy is almost 0.95. 
This mean only 5 of 100 may be wrong.

Here we have to decide on the cycle of function call, how to send to detection result to GO level and use case.

I think 2 seconds would be good as default cycle period.
And would we need to control this parameter(cycle period)?
If need, have to add some variable in "transcode_thread" structure.

Should reporting be sent immediately once detected or sent after finish transcoding process to monitoring server?
I prefer "immediately".

Should detection function be used on only PC with GPU ?
I think should be used only PC with GPU , but also need to  test on PC without GPU.

- GO Level

Some parameters should be added depending on whether use  or not detect filter.
Default setting is no use detect filter.

https://github.com/livepeer/lpms/blob/d03c749890cbbe028ab6daedf4855b711354abfd/ffmpeg/ffmpeg.go#L44

type TranscodeOptionsIn struct {
	Fname  string
	Accel  Acceleration
	Device string
	Usedetector bool
}

Usedetector : true or false (use detetion filter or not)

https://github.com/livepeer/lpms/blob/d03c749890cbbe028ab6daedf4855b711354abfd/ffmpeg/lpms_ffmpeg.h#L31

typedef struct {
  char *fname;
  struct transcode_thread *handle;
  // Optional hardware acceleration
  enum AVHWDeviceType hw_type;
  char *device;
  bool usedetector
} input_params;

usedetector : true or false (use detetion filter or not)

- Install Shell Script

For use detection filter,we need to add tensorflow install  script in "install_ffmpeg.sh" file.

## Testing Tasks and Considerations

Each new or modified behavior should have complete test coverage.

## Additional Context
In the future we can consider follwing service using ML on livepeer network.

- video surveillance service.
- video synopsis service.
- fun face masking and VR-AR service.
- online video measure service.

https://www.clarifai.com/blog/deep-learning-online-retail-growth
https://www.videosurveillance.com/
https://www.adt.com/control
https://www.briefcam.com/technology/video-synopsis/
https://visagetechnologies.com/application-fields/face-filtering/
https://www.keyence.com/solutions/case-studies/leatherman.jsp

**Comment by yondonfu** [comment]
> Avoid duplication decoding, have to insert detection function in "transcode" function, after "process_in" function.

If the detection function is implemented as an ffmpeg filter, instead of explicitly invoking the detection function could we instead include it in the [filtergraph](https://ffmpeg.org/ffmpeg-filters.html#Filtergraph-description) definition? If the filter is written following the [ffmpeg guide](https://github.com/FFmpeg/FFmpeg/blob/master/doc/writing_filters.txt), then I think the detection filter can define a callback that will receive frames that can be passed to the detection function. The ffmpeg filter writing guide also highlights a few other callbacks that might be useful to define in the filter definition. The [VMAF filter](https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_libvmaf.c) may be a useful reference here since both the detection filter and the VMAF filter output numerical values based on input frames and just passing through the input frames unchanged as output (although the VMAF filter relies on 2 videos while the detection filter relies on 1).

If we take this approach I think we can:

- In Go, when we construct the filters string for each output, include the options for the detection filter
- The filters string for each output will be used to initialize a [context](https://github.com/livepeer/lpms/blob/a15864fad1d432191ab732d0fa811a7b1d3d06be/ffmpeg/lpms_ffmpeg.c#L1275) that will be used when setting up the filtergraph
- [init_video_filters()](https://github.com/livepeer/lpms/blob/d03c749890cbbe028ab6daedf4855b711354abfd/ffmpeg/lpms_ffmpeg.c#L347) will create the filtergraph using the [filters contained in the context](https://github.com/livepeer/lpms/blob/d03c749890cbbe028ab6daedf4855b711354abfd/ffmpeg/lpms_ffmpeg.c#L337)

Since we probably don't want to run the detection function for each output maybe we can define one of the outputs as passthrough and only use the detection filter for that one?

If we take this approach I think we will need to update `install_ffmpeg.sh` to install the fork of ffmpeg that defines the detection filter.

> if probability returned is bigger than certain threshold, we can confirm this frame as indecent one

What do you think about having the detector return the probability and then the receiver of the result can use the probability however they want (i.e. they can determine if the probability meets the threshold themselves) instead of having the detector be aware of the threshold? I think the benefit of this approach is that we have one less option that we need to provide.

> Here we have to decide on the cycle of function call, how to send to detection result to GO level and use case.
> I think 2 seconds would be good as default cycle period.

If I understand correctly, I believe the cycle period determines how often the detection function is run. Could it make sense to define this period in terms of frames instead of time? For example, the detection function could be run for 1 out of every N frames. If we do this, then perhaps a counter could be defined in the [filter context](https://github.com/livepeer/lpms/blob/a15864fad1d432191ab732d0fa811a7b1d3d06be/ffmpeg/lpms_ffmpeg.c#L82) to determine when to run the detection function (i.e. increment the counter with each frame received and if the counter == N run the detection function and reset the counter).

> Some parameters should be added depending on whether use or not detect filter.

At the moment, we use a [VideoProfile](https://github.com/livepeer/lpms/blob/master/ffmpeg/videoprofile.go) to define how an input video should be transcoded. Maybe we could use video profiles to also define how a detection function should be run on an input video. Something like:

```golang
type DetectorProfile struct {
    // Run the detector on 1 out of every SampleRate frames
    SampleRate int64
    // Path to the model
    // We only have a single model right now, but this could allow updated models to be plugged in more easily?
    ModelPath string
}

type VideoProfile struct {
    Name string
    // Other fields omitted
    Detector DetectorProfile
}
```

The `Transcode()` function currently returns information about the decoded input and the encoded outputs using the [TranscodeResults](https://github.com/livepeer/lpms/blob/99fb05c90e8617ecfc3799b167d3de5600dedcf5/ffmpeg/ffmpeg.go#L67) struct. We could consider including the detector result here.

```golang
type TranscodeResults struct {
    Decoded MediaInfo
    Encoded []MediaInfo
    // Probability returned by detector
    DetectProb float64
}
```

In Go, the filters string setup in the [Transcode()](https://github.com/livepeer/lpms/blob/99fb05c90e8617ecfc3799b167d3de5600dedcf5/ffmpeg/ffmpeg.go#L172) function could look something like:

```golang
var filters string
// Add detection filter
// If the sample rate is 0 we will not include the detection filter in the filtergraph
if param.Detector.SampleRate > 0 {
    filters = fmt.Sprintf("sample_rate=%d:
}
// Add fps filter
if param.FrameRate > 0 {
    filters = fmt.Sprintf("fps=%d/1,", param.Framerate)
}
// Add scaling filter
filters += fmt.Sprintf(...)
```

**Comment by yondonfu** [comment]
Summary of some discussion from Discord:

- We can add the detection libavfilter filter in the [Livepeer fork of ffmpeg](https://github.com/livepeer/FFmpeg). Unfortunately, it doesn't look like we'll be able to maintain the filter code in LPMS because LPMS currently uses the `avfilter_graph_parse_ptr` API which depends on a constant filter list defined when ffmpeg is compiled and as a result externally defined filters cannot be registered
- We can write the result of the detection filter in a file (since the filter just outputs frames) and then the `Transcode()` function can read the result from the file if the detection filter is used

**Comment by jailuthra** [comment]
Closing as #228 fixed this
