### ISSUE TITLE
Remove B-frame In Transcoding

### ISSUE THREAD

**Issue by ericxtang** [livepeer/lpms#190]
In order to support WebRTC video ingest, we'll need to remove B-frames in our transcoding.  

As the adoption of WebRTC workflows become accelerated due to the current pandemic, there have been multiple customer requests for Livepeer to support WebRTC ingest.  Even though LPMS currently doesn't support that, as the first step, we can rely on media server integrations to support WebRTC ingest.  

We should add a parameter in our segment-based transcoding API for removing B-frames, and have our transcoder to support that feature.  This can be done by adding a "constrained baseline" transcoding profile option, which can serve as the low latency mode that suppresses B-frames.

**Comment by ericxtang** [comment]
Changed the issue description to align with the new discussion.  @j0sh can you take a look and see if this is more in line with what you are thinking about?  Also, please add any technical details not covered here.

**Comment by j0sh** [comment]
@ericxtang The request doesn't have anything to do with WebRTC ingest. Suppressing B-frames from the transcoded output is intended to support WebRTC RTP as a delivery target.

The underlying reason for B-frame suppression is that the H.264 MTI for WebRTC only requires decoders to conform to the [Constrained Baseline profile](
https://tools.ietf.org/id/draft-burman-rtcweb-h264-proposal-01.html#sec-profile-level). That's also the only profile that the [OpenH264 decoder](https://github.com/cisco/openh264/wiki#decoder-features) supports, which is the H.264 implementation used by Chrome and Firefox. The WebRTC spec also recommends Constrained High for decoders that can support it. Note that such capability negotiation is beyond our scope.

In order to support delivery of WebRTC RTP in the broadest manner possible, let's add selectable profile support to the transcoder, rather than disabling a specific feature such as B-frames. We've also had other requests to specify the H.264 profile, so this will be useful outside of WebRTC.
