### ISSUE TITLE
Create H264 Profile Option Spec

### ISSUE THREAD

**Issue by ericxtang** [livepeer/lpms#191]
We want to support H264 profiles support (baseline, main, high, high-without-B-frames).  This will allow the users to pick the transcoding profile with more granularity, and it will help us fulfill the user request of removing B frames for WebRTC delivery.

TODO: create a spec that covers the changes necessary in LPMS and go-livepeer.

**Comment by j0sh** [comment]
Dumping this out from Discord for future reference
---
2:19 PM] iameli: Is NVENC support for various profiles a concern at all? Are profiles even a hardware thing? Some cursory googling didn't get me anywhere
[2:28 PM] j0sh: Looking at the options, they have most of what we want. https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/nvenc_h264.c#L42-L46

Need to check the nvenc API docs if it can do additional profiles  beyond that such as constrained (which would need to be added to ffmpeg), or maybe we need to kludge it by setting b_ref_mode (if that's the correct option... EDIT nope, just the plain avctx.max_b_frames=0)

[2:30 PM] j0sh: yeah, the nvenc API supports it, ffmpeg just needs to be updated - 

// {AEC1BD87-E85B-48f2-84C3-98BCA6285072}
static const GUID NV_ENC_H264_PROFILE_CONSTRAINED_HIGH_GUID = 
{ 0xaec1bd87, 0xe85b, 0x48f2, { 0x84, 0xc3, 0x98, 0xbc, 0xa6, 0x28, 0x50, 0x72 } };
[2:35 PM] j0sh: Looks like it needs to be added to x264 as well (not just ffmpeg's, but actual libx264), although we can also kludge it there via encoder options (set high profile, disable bframes and interlacing)
[5:50 PM] j0sh: Okay, did a little more digging and just dumping things here for whoever to pick up later, probably Jai:

x264 added implicit support for some additional H.264 profiles (eg, you had to set the encoding knobs correctly, and that would be detected then the corresponding signaling written in the SPS/PPS), and constrained high was among those:

https://code.videolan.org/videolan/x264/commit/92d36908cbafd2a6edf7e61d69f341027b57f6f8

However, it was later disabled: 

https://code.videolan.org/videolan/x264/commit/f9af2a0f71d0fca7c1cafa7657f03a302da0ca1c

A clue as to why can be seen in the original commit message: "Even in Main profile, constraint_set4_flag is now set to 1 if progressive". and users were complaining about their main profile encodes breaking:

https://mailman.videolan.org/pipermail/x264-devel/2019-July/012689.html

The reverted commit mentions, "Some hardware decoders reject to decode streams with non-zero constraint_set4_flag/constraint_set5_flag."

Now, the bug here seems to be that the implicit setting of Progressive High was the problem, even if High alone was specified. In other words, High != Progressive High, so don't signal PH even if the encoding options would otherwise be a match. So if the usage of PH is actually made explicit, eg via a named profile in x264, rather than implicit inferring from the encoder params, then it should preserve the old behavior. Whether that'll still work on the devices that Jaron is interested in, is an open question. We can probably still get away with just setting the knobs in the encoder itself (eg, disabling interlacing and B-frames) without any explicit SPS/PPS signaling. /end dump

**Comment by jailuthra** [comment]
Created the spec here: https://github.com/livepeer/go-livepeer/issues/1531

Closing this for now. In case the *Constrained High* approach adopted in #196 does not work out with WebRTC, will create a separate issue to fix that.
