### ISSUE TITLE
Gaps after dropped segments are ignored; timestamp drifts over time

### ISSUE THREAD

**Issue by iameli** [livepeer/lpms#197]
This occurs when we're processing data that contains missing chunks, like when we're handling data from MistServer RTMP ingest and OBS looks like this:

![image](https://user-images.githubusercontent.com/257909/85639958-349b2880-b63f-11ea-96a8-f879b75380e5.png)

As far as I understand it, when we get to those dropped segments, we incorrectly treat the next frame we encounter "next" in the timecode. This results in the transcoded PTS drifting behind the source PTS over a long enough time period, here's a spreadsheet of it happening: https://docs.google.com/spreadsheets/d/1UzP5EmMuFF6rw-wlOg2vIX1fT6XPa-hto0w_qWrEkvA/edit#gid=0

Minimal repro case; transcode these three segments in sequence and then look at the discrepancies between the start and end: [sample.tar.gz](https://github.com/livepeer/lpms/files/4828510/sample.tar.gz)

Full 1GB dataset: https://storage.googleapis.com/docs.livepeer.live/eli/segment-debugging/drift.tar.gz

EDIT: We think this to be caused by changing FPS

**Comment by jailuthra** [comment]
x-posting some root cause analysis on this from discord:

The source segments seem to have some missing frames - there were weird jumps in source PTS around the 1-frame segments. The current lpms transcoder by default assumes there are no missing frames in the input, and predicts output PTS uniformly with every incoming frame (regardless of what incoming frame says its PTS is)

Thus output PTS ultimately drifts exactly the same amount as the duration of missing frames or pts jumps in the input. Analyzing timestamps of all the source-xxx.ts files in the shared tar, the drift is around 77seconds :O

Here's a sheet with the frame-wise PTS data: https://docs.google.com/spreadsheets/d/1v966abKvmHoVbWrjot1wY5HOfNYsHfCTgyF86llmplY/edit#gid=0

Here's the short bash command I used to generate it:
```for i in {376..1967}; do; ffprobe -show_frames source-$i.ts | grep pkt_pts_time >> pts.txt; done;```

*Note to future solver (probably me):* The fix would be to handle setting output PTS robustly even if source segments have dropped frames in between. Find the places where LPMS assumes happy-paths wrt source frame PTSs.
