### ISSUE TITLE
GPU encoding doesn't produce  B-frames for 'High' profile

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/lpms#238]
Tested on production - setting profile to 'high' produces segment with profile set to 'high' but without B-frames.
Transcoding locally on CPU produces segment with B-frames.

**Comment by jailuthra** [comment]
From a past discussion when we implemented H264profiles support https://github.com/livepeer/lpms/pull/196#discussion_r441664750 - NVENC by default does not produce B-frames even if we select High profile.

From https://github.com/HandBrake/HandBrake/issues/3248 and `ffmpeg -h full` it seems like we can explicitly enable `-bf #frames` to add B frames and chipsets since Turing should support it.

**Comment by darkdarkdragon** [comment]
> ```
> -bf <int> E..V....... set maximum number of B-frames between non-B-frames (from -1 to INT_MAX) (default 0)
> ```

Then why we don't enable it?

**Comment by jailuthra** [comment]
> Then why we don't enable it?

Who said we won't?

**Comment by darkdarkdragon** [comment]
> > Then why we don't enable it?
> 
> Who said we won't?

We're setting "bf" to zero here https://github.com/livepeer/lpms/blob/301900dd25100b0624104233c5ad644d9b023960/ffmpeg/ffmpeg.go#L331
But it is zero by default
https://github.com/livepeer/FFmpeg/blob/1fdf06e14239e1aaa9ddfb648fa374ca3cb1b269/libavcodec/nvenc_h264.c#L154
So we should explicitly enable B frames, but we don't.
Also, every Nvidia GPU supports B frames for h264, so we should get it once we enable it.

**Comment by jailuthra** [comment]
> We're setting "bf" to zero here
> 
> https://github.com/livepeer/lpms/blob/301900dd25100b0624104233c5ad644d9b023960/ffmpeg/ffmpeg.go#L331

That is done for the "constrained high" profile, which should have 0 B-frames by definition.

> But it is zero by default

It is not zero by default for libx264, we have to explicitly set it to enable "constrained high" profile in libx264.

> https://github.com/livepeer/FFmpeg/blob/1fdf06e14239e1aaa9ddfb648fa374ca3cb1b269/libavcodec/nvenc_h264.c#L154
> So we should explicitly enable B frames, but we don't.
> Also, every Nvidia GPU supports B frames for h264, so we should get it once we enable it.

But I agree that we should set `-bf` to non-zero for high and main profile. It was new information for me that `nvenc` encoder respects that flag when I noted it in the earlier [comment](https://github.com/livepeer/lpms/issues/238#issuecomment-859665201), and the intention since that comment is to fix it. Which is why I made the following comment :)

> Who said we won't?

and moved this issue to the ZenHub TODO.

NB: We also had a TODO in our unit tests which explicitly disabled check for B-frames in GPU renditions https://github.com/livepeer/lpms/blob/301900dd25100b0624104233c5ad644d9b023960/ffmpeg/api_test.go#L948-L957 maybe for future we should open Github Issues directly rather than TODO/FIXMEs in code that are easy to forget.

**Comment by darkdarkdragon** [comment]
@jailuthra Thanks for the explanation, now I've got it 😄 

> maybe for future we should open Github Issues directly rather than TODO/FIXMEs in code that are easy to forget.

Good idea.
