### ISSUE TITLE
Update `vf_lvpdnn` filter to use the newer APIs in ffmpeg v4.4

### ISSUE THREAD

**Issue by jailuthra** [livepeer/lpms#248]
Faced some conflicts when rebasing our DNN filter `vf_lvpdnn` on top of the [v4.4 release of ffmpeg](https://github.com/livepeer/FFmpeg/tree/jai/ffmpeg-v4.4)
 
While some conflicts could be fixed, the end result still **does not compile** as the API for loading models and setting their inputs/outputs has [changed a lot ](https://github.com/FFmpeg/FFmpeg/commits/master/libavfilter/dnn/dnn_backend_tf.c) over the past two years.

To unblock the LPMS build I disabled DNN usage as a short term solution in https://github.com/livepeer/lpms/pull/246/commits/94a8e79fcc60eaf9404e31f76a1f397e4c6e7c7e

But to successfully upgrade to v4.4 we'll need to -

- [x] Port our DNN filter to the newer APIs - Done here https://github.com/livepeer/FFmpeg/commit/b28fb9cc0cbaa4d
- [x] Ensure all requirements are met by new filter
- [x] Update LPMS to use the updated DNN filters.

**Comment by jailuthra** [comment]
Things changed on the DNN backend from 2019 to 4.4:

1. No more separate calls for `set_input_output` -> input/output is set directly everytime model is executed via `execute_model`: 
https://github.com/livepeer/FFmpeg/commit/0f7a99e37ae52f9ecdc4c81195c14b03f5be3dfd
https://github.com/livepeer/FFmpeg/commit/fce3e3e137843d86411f8868f18e1c3f472de0e5

2. Filters don't need to implement copying from incoming `AVFrame` -> `DNNData` and output `DNNData` -> outgoing `AVFrame`. All of this is moved to the DNN backend implementations, and shared across filters. Along with some of the swscale stuff used for pixel format support:
https://github.com/livepeer/FFmpeg/commit/2003e32f62d94ba75b59d70632c9f2862b383591

3. Setting Tensorflow session config (which we use for GPU device ID) added in tensorflow backend:
https://github.com/livepeer/FFmpeg/commit/c4a3dbe726150d9217a4d3fed47b012839e33d82

4. Common functions to load model via path, initialize filter, backend options etc. have moved to a separate module and datastructure `DnnContext`:
https://github.com/livepeer/FFmpeg/commit/bdce6361004b3a24082e00b6c0126e2694a65b50

5. New DnnFunctionType added like Classify/Detect/Process signalling what action the filter actually performs on the incoming AVFrames:
https://github.com/livepeer/FFmpeg/commit/76fc6879e2c59929e7d81a72986bb4950053177e

With all of this in place, some of the filters that use DNN (like super-resolution) look *much* simpler than they used to:
https://github.com/livepeer/FFmpeg/blob/jai/ffmpeg-v4.4/libavfilter/vf_sr.c
Makes it easier to maintain a filter too - if there are any more changes on the backends or in the common utilities.

I tried finding relevant blocks of code in our lvpdnn filter that we could replace - but it is very hard and all over the place right now. 

What our lvpdnn filter currently does different from a "vanilla" DNN filter:
- Accept frame samplerate - to only run the models on every nth frame.
- Accept enum for distinguishing between scene classification or object detection (currently unused)
- Copy HW frames to SW before running filtering
- Assume model is pre-loaded via the by-passed API, and user passes same parameters as the pre-loaded model. (tech debt we had to rethink anyway)

IMO it would be easier to pick one of the existing DNN filters that have all the utils in place, and modify it to support whatever LPMS expects for scene classification, including the list above. What do you all think @oscar-davids @yondonfu?

This will also allow us to use `DnnContext` as a pre-loaded model - which already contains input/output/modelpath details and make comparison easy between pre-loaded model and new filter_frame() call. I'll also take a shot at a better API for pre-loading model - but worst case will retain the global header changes we did earlier in `avfilter.h` and keep it as a techdebt.

**Comment by yondonfu** [comment]
> Setting Tensorflow session config (which we use for GPU device ID) added in tensorflow backend

This one is interesting...Based on the commit message, it sounds like the expectation is that someone would use a Python script to generate serialized proto that represents the Tensorflow session config. If we want to support a user provided list of GPU device IDs, presumably the serialized proto would need to be generated once that input is known so there is a question of how the serialized proto would be generated. Ask the user for it as a command line flag value like what is done with the ffmpeg CLI? Generate it in LPMS (can it be done using Go/C instead of Python)? 

> IMO it would be easier to pick one of the existing DNN filters that have all the utils in place, and modify it to support whatever LPMS expects for scene classification

So, this would mean using an existing DNN filter that uses the latest DNN backend APIs as a template and then porting over the logic from the lvpdnn filter following that template as opposed to trying to modify the lvpdnn filter implementation and introducing new DNN backend API calls? That does seem easier and more maintainable so sounds reasonable to me.

> This will also allow us to use DnnContext as a pre-loaded model - which already contains input/output/modelpath details and make comparison easy between pre-loaded model and new filter_frame() call.

Would be great if this means one more piece of extra logic that we can remove from our fork!

**Comment by oscar-davids** [comment]
Really there were a lot of changes in FFmpeg v4.4.
I think it is reasonable to re-update  "lvpdnn" filter based on the new version 4.4. 
Here, we have to consider "hwdownload" filter to remove the copying process from HW to SW buffer because all dnn filters such as the "vf_sr" filter do not support "AV_PIX_FMT_CUDA" format.

> Setting Tensorflow session config (which we use for GPU device ID) added in tensorflow backend


I think this session config is might appropriate for supporting one GPU but not multi GPU such as our case.So I think  we need check  that after implement them as this session way In case of multiple GPUs.
And I understand that the ["tf_sess_config.py"](https://github.com/FFmpeg/FFmpeg/blob/master/tools/python/tf_sess_config.py) script is being used to create this session string and this scipt need to install python tensorflow. I think we should study more about how to make session strings with C/GO.

**Comment by jailuthra** [comment]
> we have to consider "hwdownload" filter to remove the copying process from HW to SW buffer because all dnn filters 

nice idea on using the hwdownload filter instead of doing it in our filter. will try this out!

> Ask the user for it as a command line flag value like what is done with the ffmpeg CLI? Generate it in LPMS (can it be done using Go/C instead of Python)?

Yeah I'll try to see what all values the python script sets for the config protobuf message (other than GPU device). If they're same across environments, then makes sense to ditch the python script and generate the protobuf message ourselves in C/Go (taking the GPU device list from user)

**Comment by jailuthra** [comment]
Quick Update:
- [x] Port our filter to a new scene-classification-only filter to use newer APIs and utilities
- [x] Run and test filter accuracy. Also test with `hwdownload,format=nv12,...` when using GPU decoder. https://github.com/livepeer/FFmpeg/commit/b28fb9cc0cbaa4d
- [ ] Pre-load models for new filter - attempting a better API else falling back to old one.
- [ ] Use DNN backend's in-built TF session config setup to configure GPU settings like device ID and memory management.
