### ISSUE TITLE
Determine whether it is safe to use a single shared model in GPU mem across multiple sessions

### ISSUE THREAD

**Issue by yondonfu** [livepeer/lpms#257]
Note: Session here refers to a transcoding session, but since each transcoding session includes the creation of a TF session we can treat session to refer to both the transcoding and TF session.

If it is safe to use a single shared model then that would eliminate model loading overhead at session initialization time and decrease the overall GPU mem usage (since right now we load a new instance of the model into GPU mem whenever a session is initialized).

@oscar-davids suspects that concurrency safety may be an issue with accessing the input and output of the model. If this is the case, then we might be able to use a mutex to protect access of the input and output.

**Comment by oscar-davids** [comment]
# Design and implement thread-safe multi GPU model

## Problem
1. Support multi-GPU model loading. Currently, the raw image data gets downloaded to CPU, then uploaded back to GPU for inference. However, we want to remove this redundency.
2. Real time processing
3. Thread-safety and solve redundency issue in GPU memory occupation. When we configure TF sessions for each stream, we load models every time new stream gets added. This results in additional model load time and redundency in GPU memory occupation. In this solution, we will make model loaded once on each GPU and different stream sessions run inference on the same model.

## Solution
1. Model pre-loading. Instead of configuring dnn filtergraph and set session configuration each time new stream gets added, we will preload model on each GPU cards when the T node starts. When new stream comes in, we will run inference on the same GPU where transcoding takes place for that stream. Preloading will solve real time processing problem and make it possible to remove redundancy in GPU<->CPU data copying.
2. Setting GPU ID of models. Instead of setting GPU id by setting protobuf in the session config params, we will use [TF_ImportGraphDefOptionsSetDefaultDevice  ](https://github.com/tensorflow/tensorflow/blob/f1298f31bf7566dc0f7f1d17a394596337da12bd/tensorflow/c/c_api.h#L762)function to explicitly set the ID of model
3. Ensure thread-safety by mutex locking input and output of model(specially in coreweave box).

**Comment by yondonfu** [comment]
Closing because based on research by @cyberj0g it doesn't look like there are resource gains from switching to model sharing as sessions in TF (which are removed in a later version) don't appear to load anything extra on the same GPU. We might benefit from dynamic batching (which most inference servers support) in the future though.
