### ISSUE TITLE
`GetCodecInfo()` returns resolution of 0x0

### ISSUE THREAD

**Issue by AlexKordic** [livepeer/lpms#355]
[GetCodecInfo()](https://github.com/livepeer/lpms/blob/master/ffmpeg/ffmpeg.go#L859) returns resolution 0x0 for input segment resulting in

![bug](https://user-images.githubusercontent.com/3812017/198026995-0c8e28d1-9197-40ad-90ea-8e8727e86435.png)

**Comment by yondonfu** [comment]
@AlexKordic Can this be closed after https://github.com/livepeer/lpms/pull/358 is merged?

IIUC after that PR is merged the transcoder will start returning TranscoderInvalidVideo for these types of videos and the fix for that will be in Mist to make sure it doesn't drop video tracks during segmenting which feels like a separate issue that needs to be tracked in Mist.

**Comment by AlexKordic** [comment]
Yes. Closing.
