### ISSUE TITLE
Avoid writing broadcasted segments to disk

### ISSUE THREAD

**Issue by j0sh** [livepeer/lpms#46]
>  is there a way to stream the output segments out instead of having to rely on writing to the file system? That feels more stable (otherwise we have to pull the fs later and guess what it means when something unexpected happens)

https://gist.github.com/j0sh/05252a48edd163b01e65f1b363de1631#gistcomment-2329712

**Comment by j0sh** [comment]
What should we do with the segments right now, if we don't write them to disk? Hold them in memory then send directly to a transcoder or viewer upon request?

We can certainly avoid writing to the filesystem, but I think I'd prefer to. Here are some reasons why:

1. Writing to the filesystem would be more resilient, since the broadcaster has an on-disk record of any segments in case something goes wrong. Eg, broadcaster crashes/restarts before IPFS or a transcoder has the chance to pick up the segments, or before transcoding verification is complete.

2. Writing to filesystem makes tooling much simpler  -- we can have separate (logical) processes pick up new segments from disk then submit to IPFS, or perform post-processing, and so forth. While we might not want to ship a collection of 'critical' auxiliary scripts ourselves (UX-wise), it'd be a convenient entry point for community projects that might want to manipulate the segments.

**Comment by dob** [comment]
I'm not sure this is exactly in scope for this issue, but I wanted to point out that while it may seem like broadcasters don't necessarily need to write segments to disk, transcoders almost certainly do, at least temporarily. And aren't transcoders essentially broadcasters as well since they become the origin point for the transcoded streams? Here're some reasons why they may need to write segments to disk:

* to be able to claim transcoded segments (in general, but specifically after a node crash/restart when they may not be available in memory any longer)
* to be able to write them to IPFS during verification
* Possibly if it's requested that the stream be recorded (locally or to IPFS) - this is not a feature we have yet, but it's commonly requested.

**Comment by ericxtang** [comment]
I like that we will be able to load the files if broadcaster crashes, and agree that transcoders should write the files onto disk.

Our current approach treats the on-disk files as tmp files and have no guarantee about their existence in the future.  To improve this, we should at least organize the directories so data can be retrieved based on its StreamID and SegNo.

@dob has talked about an abstraction layer (say it's called "VideoLoader"), that can load video segments from arbitrary locations, we can then implement a "FSVideoLoader" that handles the loading from a filesystem.  Another idea I have is to have a common "Locator", so the writers and the loaders can share this and be in sync about where to write/load a video (For example, the segmenter will use the Locator to do the segmentation directly onto the fs)

**Comment by dob** [comment]
One more counterpoint to this worth mentioning, is that even though we may want the files on disk for a number of reasons, we obviously can't leave them there forever. Video would fill up the HD very quickly. So I like the idea that things are written as `/tmp` until some milestone - potentially the completion of the claim/verify/slash period for the original job. Or immediately at completion of the stream if not meant to be saved. Don't have the perfect solution, but just wanted to mention it.

**Comment by j0sh** [comment]
I guess we've settled on writing to disk for now. Closing this issue to keep the tracker clean, but feel free to re-open if there's still more to discuss in this area.
