### ISSUE TITLE
Adaptive Bitrate Streaming for livepeer.tv

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/lpms#66]
Currently I am broadcasting in 1920x1080 for livepeer.tv

For my viewers to be able to watch, they must have

- a fast enough internet connection to be able to receive the feed
- a powerful enough device to show the content

I would like to be able to serve the content at different resolutions (and bit rates) so that viewers with less powerful internet connections and devices can still watch.

**Comment by ericxtang** [comment]
We could make `m.livepeer.tv` automatically select the low resolution version if it's available.

**Comment by dob** [comment]
Not that we live up to this with full reliability, but isn't this exactly what *should* be occurring automatically via our ABS transcoding and hls.js player?

**Comment by chrishobcroft** [comment]
Do you mean "Transcoding"?

**Comment by chrishobcroft** [comment]
This solution is particularly important when considering accessibility to a more diverse and global audience.

I will close this issue, and open another in a different place.

**Comment by jozanza** [comment]
@dob @chrishobcroft indeed, the video player *should* automatically select the highest bitrate available that will play smoothly on the user's device and internet connection. Problem is it's hard to confirm since streams transcoded on the network don't ever seem to contain multiple bitrates. So to move forward, we either need to spend some time debugging the player with some sample m3u8 files or we need a transcoder that produces multiple bitrates.

**Comment by dob** [comment]
Related to this very good point from @jozanza about streams on the network rarely or never containing multiple bitrates - this is the number one reason I'm pushing for visibility into the # of segments of video transcoded by each transcoder over some timeframe on the transcoder election view of the dashboard. Even though it's not super affordable on mainnet to use this for all use cases yet, the visibility into how much work transcoders are doing would allow us to start testing, debugging, and putting pressure on transcoders to be online and perform.

It would help the whole system get ready for production, even if we have to fund some of the fees through the network by funding the ETH costs for broadcasters such as livepeer.tv in the short term. 

If we start to make these video statistics visible, and transcoders get elected based upon their performance and reliability as a major factor, it will help to push the network to be ready for scale when we can address cost.

Anyway, I know this discussion doesn't necessarily belong in this issue, but wanted to point it out since it's very much related to why we don't see multiple bitrates in the player at the moment.
